### ISSUE TITLE
Receiving a "Torch not compiled with CUDA enabled" error while setting up the environment

### ISSUE THREAD

**Issue by nisargvp** [PacktPublishing/Modern-Time-Series-Forecasting-with-Python#1]
I am using a windows 11 machine with a NVIDIA 3070 with the correct pytorch and cuda versions installed but despite all my efforts of setting up the environment or manually installing pytorch and cuda via conda / pip does not allow me to use my gpu. The error is flagged by the test_installation.py file Any help is appreciated!

**Comment by manujosephv** [comment]
Hi @nisargvp,

This is an issue with PyTorch installation. Looks like you installed PyTorch without CUDA support. https://pytorch.org/ has instructions for how to install PyTorch with cuda support.

Something like:
`conda install -c pytorch torchvision cudatoolkit=10.1 pytorch`
depending on your CUDA version.

Here are a few links to help you debug it

https://github.com/pytorch/pytorch/issues/30664
https://discuss.pytorch.org/t/torch-not-compiled-with-cuda-enabled/112467/14

**Comment by nisargvp** [comment]
Thanks for the quick response @manujosephv . I did try the process mentioned on the pytorch website but it seems like despite using the correct conda install procedure for pytorch with cuda support it continues to uinstall a cpu-only version of pytorch. I eventually made it work by uninstalling the conda version and using pip3 to install pytorch and update any subsequent conflicts. Hoping it won't cause any pain down the road as I go through the book (finger crossed) :)

**Comment by manujosephv** [comment]
It shouldn't... Good luck.. :)
