### ISSUE TITLE
Data structure is not correct

### ISSUE THREAD

**Issue by 3zhang** [PacktPublishing/Modern-Time-Series-Forecasting-with-Python#10]
In book preface xxii - xxiii, the data structure is depicted as:
data
├── london_smart_meters
│   ├── hhblock_dataset
│   │   ├── hhblock_dataset
│   │       ├── block_0.csv
│   │       ├── block_1.csv
│   │       ├── ...
│   │       ├── block_109.csv
│── acorn_details.csv
├── informations_households.csv
├── uk_bank_holidays.csv
├── weather_daily_darksky.csv
├── weather_hourly_darksky.csv

But based on the test code, the data structure should be like this:
data
├── london_smart_meters
│   ├── hhblock_dataset
│   │   ├── hhblock_dataset
│   │       ├── block_0.csv
│   │       ├── block_1.csv
│   │       ├── ...
│   │       ├── block_109.csv
│   ├── acorn_details.csv
│   ├── nformations_households.csv
│   ├── uk_bank_holidays.csv
│   ├── weather_daily_darksky.csv
│   ├──  weather_hourly_darksky.csv

**Comment by manujosephv** [comment]
closing this because its rectified in Readme and added to Errata so that we can rectify this in the book
