### ISSUE TITLE
issue creating parquet format file

### ISSUE THREAD

**Issue by mitch-bollinger** [PacktPublishing/Modern-Time-Series-Forecasting-with-Python#14]
For some reason the dataframe in notebook "02 - Preprocessing London Smart Meter Dataset" does not seem to be able to convert to Parquet format per this screen shot. I have tried setting the encoder to both fastparquet and pyarrow but still no luck. This would not be a problem except for the fact that the next chapter relies on this file so I am sort of stuck until I figure it out. Any ideas?

![image](https://user-images.githubusercontent.com/57966900/223212819-7be1d7de-5eb4-407d-a901-69d2f9aa2c14.png)

**Comment by manujosephv** [comment]
Are you getting the same error for `pyarrow`? 

And as a workaround, you can save the dataframe as a pickle or some other format and in future chapters, when reading, use the same format. Although Pickle did take up a lot of space and time when I tried it.

**Comment by mitch-bollinger** [comment]
Thanks so much for the feedback. I got back on it today and started over and it worked this time. Best I can guess pyarrow and fastparquet has installed but perhaps but starting over with a new kernel they worked this time.

Also, this book is great as it is quite a challenge for someone like me who does not have an extensive Python programming background. But this is how you get good at it, learning from people who have a lot more experience.

**Comment by manujosephv** [comment]
Glad you figured it out. closing the issue.
