### ISSUE TITLE
Naive Moving Forecast error

### ISSUE THREAD

**Issue by mitch-bollinger** [PacktPublishing/Modern-Time-Series-Forecasting-with-Python#15]
I am getting this error for the NaiveMovingAverage class. I am playing around with it try and figure it out but no luck yet. Any ideas?

![image](https://user-images.githubusercontent.com/57966900/223795736-2a1ba79a-fa5f-42fc-851e-3b4e72930c02.png)

**Comment by manujosephv** [comment]
I assume this is working. Closing the issue
