### ISSUE TITLE
window_ops.rolling issue

### ISSUE THREAD

**Issue by mitch-bollinger** [PacktPublishing/Modern-Time-Series-Forecasting-with-Python#16]
Looks like something strange is going on here.

![image](https://user-images.githubusercontent.com/57966900/224417614-9bb469ed-0f86-4000-934b-f0eeab84e751.png)

**Comment by manujosephv** [comment]
I guess there is some problem with the environment. `windows_ops` should have that method.

**Comment by manujosephv** [comment]
I just cjecked on latest version of `window_ops` also and the method is still [there](https://github.com/jmoralez/window_ops/blob/799364406cf542619514af7bb3dd55d93b5ab064/window_ops/rolling.py#L166)

Closing the issue
