### ISSUE TITLE
Chapter 13 - RuntimeError: mat1 and mat2 shapes cannot be multiplied (1536x256 and 128x1)

### ISSUE THREAD

**Issue by nonpa-gt** [PacktPublishing/Modern-Time-Series-Forecasting-with-Python#17]
Please a little help

I am running the exercises but I found the following error, I have managed to solve the previous .ipynb  issues but this one has taken me a long time.

I got the following error in the line 17th

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1536x256 and 128x1)

I attach an image of the error... 

![image](https://user-images.githubusercontent.com/70252999/225788983-760437b7-b854-4312-9341-741e01f36991.png)

**Comment by manujosephv** [comment]
I suspect this is because of a bug fix I pushed recently... I'll take a look at this and get back.. Also, if you have faced some other problems (and even better solved it), please post it here so that others can benefit from that..

**Comment by nonpa-gt** [comment]
> I suspect this is because of a bug fix I pushed recently... I'll take a look at this and get back.. Also, if you have faced some other problems (and even better solved it), please post it here so that others can benefit from that..

Oh thank you for your answer, I will try to remember most of the problems I faced which are the following:

- Need to add libraries to .yml file (tsfel, pymannkendall, window-ops, pytorch_tabular)

- Chapter02 01 -Pandas Refresher ... code block line 37 and 38:
The data downloaded from "https://www.data.act.gov.au/resource/94a5-zqnn.csv" only contains the last month so you need to change the date values in line 38: (for March 2023)


df = df.loc["2023-03-01 7:00":"2023-03-14 16:00", "pm2_5_1_hr"].to_frame()
 

- In case you are running pytorch without gpu support:

Found all the TrainerConfig(). ... and change the following lines:
     ...     
     auto_select_gpus=True,
     gpus=-1

**change it for:**
    #auto_select_gpus=True,
    accelerator = 'cpu',
    gpus=None #-1

-

**Comment by sfa77** [comment]
Same here. Pls help

I also confirm @nonpa-gt discovery with commenting gpus=-1 line.

**Comment by manujosephv** [comment]
#21 Should have fixed this. It would be nice if someone can check and confirm

**Comment by sfa77** [comment]
verified, pls close the issue
