### ISSUE TITLE
automated data download error

### ISSUE THREAD

**Issue by nisargvp** [PacktPublishing/Modern-Time-Series-Forecasting-with-Python#2]
Hi - 
Sorry to bother but I'm receiving the following erorr while running the download_data script in my root directory "ModuleNotFoundError: No module named 'logger_api'", it occurs on line 8, from logger_api import get_logger. Appreciate it, if you can help with this.

Thanks again!

**Comment by manujosephv** [comment]
Good catch. For some reason the logger_api file is inside the src.

can you change line 8
```python
from logger_api import get_logger
```
to
```python
from src.logger_api import get_logger
```
And see if it works? If yes, I'll edit the file in the github

**Comment by nisargvp** [comment]
Its giving me a new error: ModuleNotFoundError: No module named 'src.logger_api'. Do I need to import anything prior to this line?

**Comment by nisargvp** [comment]
I was able to resolve it using: 

import logging
logger = logging.getLogger(__name__)

furthermore, exists() did not return True for the api_keys/kaggle.json path - I simply pasted kaggle.json in the root directory which finally worked.

**Comment by manujosephv** [comment]
Glad you were able to resolve it.  I've corrected the logger issue in the main branch

the kaggle.json issue shouldn't be occurring. I wonder why. It works well for me.
the code looks for the api key in `api_keys/kaggle.json`. The folder you are in when you invoke the download_data.py should the root folder with `api_keys` folder.

**Comment by nisargvp** [comment]
Thanks. Yeah, I agree with the kaggle.json issue shouldn't be occurring- I think it might be some idiosyncrasy associated with interpreting a windows path although changing it to a string did not work either, moving it to the root directory was a last resort.
