### ISSUE TITLE
Environment Issues on M1 pro 

### ISSUE THREAD

**Issue by YendaRamSurya** [PacktPublishing/Modern-Time-Series-Forecasting-with-Python#20]
The Environment is crashing after installing with the suggested changes, utilizing the the new anaconda_env.yml 
In anaconda_env.yml, change the line python-kaleido==0.1.0 to python-kaleido>=0.1.0
In anaconda_env.yml, change the line statsforecast==0.6.0 to statsforecast>=0.6.0

Following error is noticed on Jupyter notebooks after installing the environment, a simple numpy import has failed 
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/63895091/236108187-fa3e2f7c-e44c-4e65-8564-15bda95f27ee.png">
Canceled future for execute_request message before replies were done
The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. 

Additionally, following error is noticed on terminal: 

Modern-Time-Series-Forecasting-with-Python % python 
Python 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:54:06) 
[Clang 11.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
Intel MKL FATAL ERROR: This system does not meet the minimum requirements for use of the Intel(R) Math Kernel Library.
The processor must support the Intel(R) Supplemental Streaming SIMD Extensions 3 (Intel(R) SSSE3) instructions.
The processor must support the Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) instructions.
The processor must support the Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

Looking forward to the help.

**Comment by manujosephv** [comment]
Same issue on issue #4. Closing this in favor of the other one. Check the discussion. There are a few things that may be able to help you
