### ISSUE TITLE
Chapter 04 - Kaboudan Metric 

### ISSUE THREAD

**Issue by B8ni** [PacktPublishing/Modern-Time-Series-Forecasting-with-Python#22]
I noticed an error in the book regarding the explanation of the Kaboudan metric. The current explanation states that if a time series is predictable, the Kaboudan metric approaches zero, and if it is not predictable, the metric approaches one. However, this is incorrect.
![image](https://github.com/PacktPublishing/Modern-Time-Series-Forecasting-with-Python/assets/100468506/e3c8f3c3-2b5e-41f2-9f81-5b3ee6f79f5a)

According to the correct interpretation of the Kaboudan metric, if a time series contains predictable patterns, the metric should approach one, indicating higher predictability. Conversely, if the time series lacks predictability, the metric should approach zero.

Thank you for your attention to this matter.

**Comment by manujosephv** [comment]
Thank you for the report. It is already added to the ERRATA document in the repo and will be fixed in the next edition...
