### ISSUE TITLE
Chapter 13) output tensor dimension error 

### ISSUE THREAD

**Issue by woojin716** [PacktPublishing/Modern-Time-Series-Forecasting-with-Python#24]
In Multi-step prediction section of chapter 13 (LSTM-FC Seq2Seq Last Hidden, LSTM-FC Seq2Seq All Hidden) I got RuntimeError: Predictions and targets are expected to have the same shape, but got torch.Size([32, 1, 48]) and torch.Size([32, 48, 1]).

src/dl/models.py Line 361, 363 should be fixed to "unsqueeze(-1)" or something. (forward function part of Seq2SeqModel class)

```
if self.hparams.decoder_type == "FC":
            if self.hparams.decoder_use_all_hidden:
                y_hat = self.decoder(o.reshape(o.size(0), -1)).unsqueeze(-1)  # fixed
            else: 
                y_hat = self.decoder(o[:, -1, :]).unsqueeze(-1)  # fixed
```

**Comment by manujosephv** [comment]
Thank you @woojin716. The unsqueeze(-1) does look like the right way to go. Have changed it in the code
