### ISSUE TITLE
Abstract method supports_multivariate not implemented in baselines.py

### ISSUE THREAD

**Issue by KarimABOUSSELHAM** [PacktPublishing/Modern-Time-Series-Forecasting-with-Python#31]
Hello,
I think there is an abstract method called "supports_multivariate" which should be implemented in the script baselines.py. Otherwise,we can't instantiate the abstract class "NaiveMovingAverage".

I suggest to add simply this piece of code in the aforementioned class:

  def supports_multivariate(self) -> bool:
        return True

**Comment by manujosephv** [comment]
maybe a new change in latest darts version. Can you raise a PR for this?

**Comment by manujosephv** [comment]
have pushed in a fix for this in #36
