### ISSUE TITLE
TypeError: Passing a set as an indexer is not supported. Use a list instead. Occured in Chapter08.

### ISSUE THREAD

**Issue by AhmedGillani** [PacktPublishing/Modern-Time-Series-Forecasting-with-Python#35]
I faced this issue when I was running 01-Forecasting with ML.ipynb file, the following error occurred when I executed the Sample Household block.
The error originated from src/forecasting/ml_forecasting.py --- line 153
             df.loc[:, set(feature_list + self.index_cols)]
The reason of this error is that sets are not hashable and, therefore, cannot be used as an index.
so, I replace that line with the following:
           df.loc[:, list(set(feature_list + self.index_cols))]
and it worked.

**Comment by manujosephv** [comment]
Thanks for pointing it out.. Will change it in the code

**Comment by ArjunVarma39** [comment]
Hi @AhmedGillani, I am closing this issue for now, please reopen if this issue persists.
