### ISSUE TITLE
Wrong Paths

### ISSUE THREAD

**Issue by baniasbaabe** [PacktPublishing/Modern-Time-Series-Forecasting-with-Python#6]
I noticed that in some notebooks (e.g. https://github.com/PacktPublishing/Modern-Time-Series-Forecasting-with-Python/blob/main/notebooks/Chapter03/03-Outlier%20Detection%20and%20Treatment.ipynb), the Path to the preprocessed data is wrong. 

Wrong: `preprocessed = Path("data/london_smart_meters/proprocessed")`

Right: `preprocessed = Path("data/london_smart_meters/preprocessed")`

**Comment by manujosephv** [comment]
Thanks a lot @baniasbaabe  I'll do a search and replace and edit the notebooks

**Comment by manujosephv** [comment]
Done! Closing this
