### ISSUE TITLE
python test_installation.py => AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by samerghosn** [PacktPublishing/Modern-Time-Series-Forecasting-with-Python#7]
```
(modern_ts) D:\PycharmProjects\Modern-Time-Series-Forecasting-with-Python>python test_installation.py
Traceback (most recent call last):
```

>   File "D:\PycharmProjects\Modern-Time-Series-Forecasting-with-Python\test_installation.py", line 8, in <module>
>     f"GPU: {torch.cuda.is_available()} | # of GPU: {torch.cuda.device_count()}| Default GPU Name: {torch.cuda.get_device_name(0)}"
>   File "D:\Anaconda\envs\modern_ts\lib\site-packages\torch\cuda\__init__.py", line 341, in get_device_name
>     return get_device_properties(device).name
>   File "D:\Anaconda\envs\modern_ts\lib\site-packages\torch\cuda\__init__.py", line 371, in get_device_properties
>     _lazy_init()  # will define _get_device_properties
>   File "D:\Anaconda\envs\modern_ts\lib\site-packages\torch\cuda\__init__.py", line 221, in _lazy_init
>     raise AssertionError("Torch not compiled with CUDA enabled")
> AssertionError: Torch not compiled with CUDA enabled

**Comment by manujosephv** [comment]
Are you running this on a GPU-enabled machine?

**Comment by samerghosn** [comment]
Yes, but GPU caused problems before, can I assume that the installation is correct even with this error?

I used the Yml file.

**Comment by manujosephv** [comment]
That just means the PyTorch that is installed isn't configured to use GPUs. You may want to re-install [PyTorch](https://pytorch.org/get-started/locally/). The code should work, but the deep learning training will be using CPU and that will be really slow.

**Comment by manujosephv** [comment]
hope this is resolved. Closing this
