### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'normalize' from src.decomposition.seasonal import MultiSeasonalDecomposition,STL

### ISSUE THREAD

**Issue by dieguisgs** [PacktPublishing/Modern-Time-Series-Forecasting-with-Python#8]
While executing this piece of code in 01-Visualizing Time Series.ipynb i obtain the following error:

TypeError: __init__() got an unexpected keyword argument 'normalize'

![Captura](https://user-images.githubusercontent.com/61083270/219174491-94609531-3b99-42cf-abc8-4f243178df1b.JPG)

I set correctly the conda environment

**Comment by manujosephv** [comment]
I did not fix the dependency for `scikit-learn` and in the recent update, they removed this parameter.

Immediate fix is to downgrade sci-kit learn to 1.1

`pip install scikit-learn==1.1.3`

In the meantime, I can update the code to make it work with the new version as well.

**Comment by dieguisgs** [comment]
That would be great. Thanks!
